- src: https://gitlab.com/ansible-roles-mrrrdab/ansible-role-docker
  scm: git
  version: origin/master
  name: docker

- src: https://gitlab.com/ansible-roles-mrrrdab/ansible-role-nginx
  scm: git
  version: origin/main
  name: nginx

- src: https://gitlab.com/ansible-roles-mrrrdab/ansible-role-openvpn
  scm: git
  version: origin/main
  name: openvpn
